### ISSUE TITLE
compiler error / typo with RBQFetchedResultsController

### ISSUE THREAD

**Issue by skydivedan** [bigfish24/ABFRealmGridController#7]
RBQFetchedResultsController just got updated, and the fixed a typo. 

So, the private routine `updateFetchedResultsController()`, no longer compiles.

The last argument label in `self.fetchedResultsController.updateFetchRequest` was "andPeformFetch". It is now changed to "andPerformFetch" in 4.0 of RBQ, spelling "perform" correctly.

**Comment by bigfish24** [comment]
Yeah actually I want to refactor to remove RBQFRC entirely since Realm now offers the necessary notifications directly.

**Comment by skydivedan** [comment]
ah, OK, yeah that would make sense. In the meantime, I put in a PR to fix the issue until that refactoring gets in there.

**Comment by bigfish24** [comment]
Fixed in v1.5
